version: "3.9"

services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command: mkdocs serve -a 0.0.0.0:8000
    user: "1000:1000"  # Adjust this to match your local user UID:GID if needed

