# Project information
site_name: Web Scraper Documentation
site_description: Comprehensive documentation for Web Scraper
site_author: Valentins Fedotovs

# Site URL for SEO (optional)
site_url: https://propertydata.lv/


theme:
  name: material
  palette:
    scheme: slate  # Use the 'slate' scheme for a dark theme
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-sunny  # Icon for light mode
      name: Switch to light mode
    toggle:
      icon: material/weather-night  # Icon for dark mode
      name: Switch to dark mode


nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
  - User Guide:
      - Overview: user-guide/overview.md
      - Features: user-guide/features.md
      - FAQ: user-guide/faq.md
  - About:
      - Contact: about/contact.md

markdown_extensions:
  - admonition  # For notes, warnings, etc.
  - toc:        # Table of contents
      permalink: true
  - codehilite: # Syntax highlighting for code blocks
      guess_lang: false
  - pymdownx.superfences  # Enhanced code block handling
  - pymdownx.betterem:    # Improved emphasis handling (e.g., *italic*)

plugins:
  - search  # Built-in search functionality
  - charts

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite


repo_url: https://github.com/vfedotovs/ws-web
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vfedotovs


