# Project information
site_name: Web Scraper Documentation
site_description: Comprehensive documentation for Web Scraper
site_author: Valentins Fedotovs

# Site URL for SEO (optional)
site_url: https://ws-web.pages.dev/

# Theme settings
theme:
  name: material
  # logo: images/logo.png  # Path to your logo image
  # favicon: images/favicon.ico  # Path to your favicon
  # palette:
  #   primary: 'navy'  # Change from 'blue' to 'navy'
  #   accent: 'light blue'
  # font:
  #   text: 'Roboto'
  #   code: 'Roboto Mono'

  palette:
    scheme: slate  # Use the 'slate' scheme for a dark theme
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-sunny  # Icon for light mode
      name: Switch to light mode
    toggle:
      icon: material/weather-night  # Icon for dark mode
      name: Switch to dark mode
# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Installation: getting-started/installation.md
  - User Guide:
      - Overview: user-guide/overview.md
      - Features: user-guide/features.md
      - FAQ: user-guide/faq.md
  - API Reference:
      - Endpoints: api-reference/endpoints.md
      - Authentication: api-reference/authentication.md
  - About:
      - Team: about/team.md
      - Contact: about/contact.md

# Markdown extensions
markdown_extensions:
  - admonition  # For notes, warnings, etc.
  - toc:        # Table of contents
      permalink: true
  - codehilite: # Syntax highlighting for code blocks
      guess_lang: false
  - pymdownx.superfences  # Enhanced code block handling
  - pymdownx.betterem:    # Improved emphasis handling (e.g., *italic*)

# Plugins (optional)
plugins:
  - search  # Built-in search functionality
  # - mkdocs-mermaid2-plugin  # For Mermaid diagrams
  # - mkdocs-material-extensions  # Additional features for Material theme

# Extra CSS and JavaScript (optional)
extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js

# Repository link (optional)
repo_url: https://github.com/vfedotovs/ws-web
repo_name: GitHub

# Additional configuration options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vfedotovs


